version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pipeline-testing-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18l30lxtao66v"
s3_prefix = "pipeline-testing-app"
region = "us-east-2"
profile = "pradeep"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
